pull_request_rules: []

commands_restrictions:
  queue:
    conditions:
      - sender = vm5-prefix-alias-never-allowed

merge_queue:
  mode: parallel

queue_rules:
  - name: default
    batch_size: 1
    queue_conditions: []
    merge_conditions:
      - label = vm5-prefix-alias-never-merge
    merge_method: merge
